### PR TITLE
Fix/PLF-8309: Fix scroll down of forum body while image is opened

### PR DESCRIPTION
**Pull request by hbenali3**
While a user opens an attached picture inside the forum. There is the issue of the infinite scroll in the body.

### CODE REVIEW

**Comment by hbenali** [comment]
Actually. I don't. However disabling the scroll when the image is displayed avoids any further css issues (like infinite scroll). Also IMO, the user does not need to scroll the page when the image is opened. If you have a better solution, could you please provide me ? thanks.

**Comment by thomasdelhomenie** [comment]
I checked on other pages, the behavior is not the same. For example when creating a space, we can scroll the page and there is no infinite scroll. That's being said, blocking the scroll seems to be the best choice in term of UX indeed.
I have 2 feedbacks:
* we generally avoid to change style directly in js, but instead use css class (the js only adds and removes the class on the html element). It is also easier to override if necessary. So I suggest to add a new css class (containing overflow:hidden) and add/remove it via js (that's what bootstrap does, with a class called `modal-open`). WDYT ?
* do we still need the method `scrollHandler` ? It seems responsible of the scrolling, but with this change, there is no more scroll.

**Comment by hbenali** [comment]
Well I removed the scrollhandler. but i have tried to inject a css class into the page head by js, jQuery However it doesn't work... The used framework prevents the injection. In addition i thought to add it into the eXo Skins as a new class which is little bit ugly IMO. i have tried with gj(root), gj(document), document. but nothing happens. What do you suggest ?

**Comment by thomasdelhomenie** [comment]
You mean you tried `$(document.body).addClass('myClass')` and `$('body').addClass('myClass')`, but none of them work ?

**Comment by hbenali** [comment]
I get stuck in the injection of a new class named ".noscroll" in the page by js.

**Pull request closed without merging**
