### PR TITLE
[FORUM-1224] disable processing of users moderation list when rendering a forum

### PR DESCRIPTION
**Pull request by wkhessairi**

### CODE REVIEW

**Comment by thomasdelhomenie** [comment]
Why did you create a new PR instead of updating the existing one (https://github.com/exodev/forum/pull/25) ?

**Comment by wkhessairi** [comment]
I wanted to cleanup the commit of unchanged lines

**Comment by thomasdelhomenie** [comment]
So please do it in https://github.com/exodev/forum/pull/25 by adding a new commit, and close this one.

**Comment by wkhessairi** [comment]
in fact I have already merged this one which is a copy of #25 but without EOL characters issue. I cannot do it in #25 because it already contains EOL issues.

**Comment by thomasdelhomenie** [comment]
You should have been able to add a new commit in https://github.com/exodev/forum/pull/25 to remove the EOL issues.
Since it is already merged, let's keep it like that, but for next PRs please take care to use only 1 PR.

**Comment by wkhessairi** [comment]
Ok, sorry for any inconvenience it was caused by IDE. I fixed it using vi to keep the same characters encoding.

**Comment by thomasdelhomenie** [comment]
Merged

**Pull request closed without merging**
